//! Generates Specta bindings for synth wire/domain contracts.
//!
//! Run with:
//!   cargo run --features specta-bindings --bin export-specta-bindings
//!
//! Optional env vars:
//! - SPECTA_TS_EXPORT_PATH: absolute/relative path to generated TypeScript file

use cosmo_synth_engine::params::{
    ChorusParams, DelayParams, EnvStep, FilterParams, FilterType, LfoParams, LfoTarget,
    LfoWaveform, LineParams, LineSelect, ModMode, PolyMode, PortamentoMode, PortamentoParams,
    ReverbParams, StepEnvData, SynthParams, VelocityTarget, VibratoParams, WindowType, CzAlgo,
    CzLineParams, CzWaveform, AlgoControlValueV1,
    Algo,
};
use cosmo_synth_engine::generators::{
    AlgoControlAssignmentV1, AlgoControlKindV1, AlgoControlOptionV1, AlgoControlV1,
    AlgoDefinitionV1, AlgoUiEntryV1, CzPresetV1,
};
use cosmo_synth_engine::preset_wire::{
    algo_definitions_v1, algo_ui_catalog_v1, cz_presets, SynthPresetV1,
};
use specta_typescript::{export, Typescript};

fn main() {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");

    let ts_path = std::env::var("SPECTA_TS_EXPORT_PATH").unwrap_or_else(|_| {
        format!("{manifest_dir}/../cz-explorer/src/lib/synth/bindings/synth.ts")
    });

    if let Some(ts_parent) = std::path::Path::new(&ts_path).parent() {
        std::fs::create_dir_all(ts_parent)
            .unwrap_or_else(|e| panic!("Failed to create TS output dir '{ts_parent:?}': {e}"));
    }

    let config = Typescript::default();
    let mut out = String::new();
    out.push_str("// Generated by Specta. Do not edit manually.\n\n");
    // TODO: Replace this manual export list with automated graph export when
    // the workspace can move to a Specta toolchain version that supports it.
    out.push_str(&export::<EnvStep>(&config).expect("Failed to export EnvStep"));
    out.push_str("\n\n");
    out.push_str(&export::<StepEnvData>(&config).expect("Failed to export StepEnvData"));
    out.push_str("\n\n");
    out.push_str(&export::<CzAlgo>(&config).expect("Failed to export CzAlgo"));
    out.push_str("\n\n");
    out.push_str(&export::<CzWaveform>(&config).expect("Failed to export CzWaveform"));
    out.push_str("\n\n");
    out.push_str(&export::<CzLineParams>(&config).expect("Failed to export CzLineParams"));
    out.push_str("\n\n");
    out.push_str(&export::<Algo>(&config).expect("Failed to export Algo"));
    out.push_str("\n\n");
    out.push_str(&export::<WindowType>(&config).expect("Failed to export WindowType"));
    out.push_str("\n\n");
    out.push_str(&export::<LineSelect>(&config).expect("Failed to export LineSelect"));
    out.push_str("\n\n");
    out.push_str(&export::<ModMode>(&config).expect("Failed to export ModMode"));
    out.push_str("\n\n");
    out.push_str(&export::<PolyMode>(&config).expect("Failed to export PolyMode"));
    out.push_str("\n\n");
    out.push_str(&export::<VelocityTarget>(&config).expect("Failed to export VelocityTarget"));
    out.push_str("\n\n");
    out.push_str(&export::<LfoWaveform>(&config).expect("Failed to export LfoWaveform"));
    out.push_str("\n\n");
    out.push_str(&export::<FilterType>(&config).expect("Failed to export FilterType"));
    out.push_str("\n\n");
    out.push_str(&export::<PortamentoMode>(&config).expect("Failed to export PortamentoMode"));
    out.push_str("\n\n");
    out.push_str(&export::<LfoTarget>(&config).expect("Failed to export LfoTarget"));
    out.push_str("\n\n");
    out.push_str(&export::<ChorusParams>(&config).expect("Failed to export ChorusParams"));
    out.push_str("\n\n");
    out.push_str(&export::<DelayParams>(&config).expect("Failed to export DelayParams"));
    out.push_str("\n\n");
    out.push_str(&export::<ReverbParams>(&config).expect("Failed to export ReverbParams"));
    out.push_str("\n\n");
    out.push_str(&export::<VibratoParams>(&config).expect("Failed to export VibratoParams"));
    out.push_str("\n\n");
    out.push_str(&export::<PortamentoParams>(&config).expect("Failed to export PortamentoParams"));
    out.push_str("\n\n");
    out.push_str(&export::<LfoParams>(&config).expect("Failed to export LfoParams"));
    out.push_str("\n\n");
    out.push_str(&export::<FilterParams>(&config).expect("Failed to export FilterParams"));
    out.push_str("\n\n");
    out.push_str(&export::<AlgoControlValueV1>(&config).expect("Failed to export AlgoControlValueV1"));
    out.push_str("\n\n");
    out.push_str(&export::<LineParams>(&config).expect("Failed to export LineParams"));
    out.push_str("\n\n");
    out.push_str(&export::<AlgoControlKindV1>(&config).expect("Failed to export AlgoControlKindV1"));
    out.push_str("\n\n");
    out.push_str(&export::<AlgoControlAssignmentV1>(&config).expect("Failed to export AlgoControlAssignmentV1"));
    out.push_str("\n\n");
    out.push_str(&export::<AlgoControlOptionV1>(&config).expect("Failed to export AlgoControlOptionV1"));
    out.push_str("\n\n");
    out.push_str(&export::<AlgoControlV1>(&config).expect("Failed to export AlgoControlV1"));
    out.push_str("\n\n");
    out.push_str(&export::<AlgoDefinitionV1>(&config).expect("Failed to export AlgoDefinitionV1"));
    out.push_str("\n\n");
    out.push_str(&export::<AlgoUiEntryV1>(&config).expect("Failed to export AlgoUiEntryV1"));
    out.push_str("\n\n");
    out.push_str(&export::<SynthParams>(&config).expect("Failed to export SynthParams"));
    out.push_str("\n\n");
    out.push_str(&export::<SynthPresetV1>(&config).expect("Failed to export SynthPresetV1"));
    out.push_str("\n\n");
    out.push_str(&export::<CzPresetV1>(&config).expect("Failed to export CzPresetV1"));
    out.push_str("\n\n");
    let catalog_json = serde_json::to_string_pretty(algo_ui_catalog_v1())
        .expect("Failed to serialize ALGO_UI_CATALOG_V1");
    let definitions_json = serde_json::to_string_pretty(algo_definitions_v1())
        .expect("Failed to serialize ALGO_DEFINITIONS_V1");
    out.push_str("\n\n");
    out.push_str("/** Rust-owned algorithm UI catalog. */\n");
    out.push_str("export const ALGO_UI_CATALOG_V1: AlgoUiEntryV1[] = ");
    out.push_str(&catalog_json);
    out.push_str(";\n");
    out.push_str("\n");
    out.push_str("/** Rust-owned algorithm definitions and control defaults. */\n");
    out.push_str("export const ALGO_DEFINITIONS_V1 = ");
    out.push_str(&definitions_json);
    out.push_str(";\n");
    out.push_str("\n");
    let cz_presets_json = serde_json::to_string_pretty(cz_presets())
        .expect("Failed to serialize CZ_PRESETS");
    out.push_str("/** Rust-owned CZ waveform combination presets. */\n");
    out.push_str("export const CZ_PRESETS: CzPresetV1[] = ");
    out.push_str(&cz_presets_json);
    out.push_str(";\n");

    std::fs::write(&ts_path, out)
        .unwrap_or_else(|e| panic!("Failed to write TypeScript bindings to '{ts_path}': {e}"));

    println!("[specta-bindings] Exported TypeScript bindings to: {ts_path}");
}
