// Generated by Specta. Do not edit manually.

/**
 * A single step in a step envelope
 */
export type EnvStep = { 
/**
 * Level [0.0, 1.0]
 */
level: number; 
/**
 * Rate [0, 99] — JS may send floats; we round to u8.
 */
rate: number }

/**
 * Step envelope data (CZ-style)
 * 
 * Field names match the JS `StepEnvData` type exactly (camelCase).
 * `steps` is always stored as a fixed [EnvStep; 8] internally; JS may
 * send a shorter array which gets padded with silent steps.
 */
export type StepEnvData = { steps: EnvStep[]; 
/**
 * Which step to sustain on (0-based index into steps)
 */
sustainStep: number; 
/**
 * Number of active steps (JS `stepCount`)
 */
stepCount: number; 
/**
 * Whether envelope loops after end
 */
loop: boolean }

/**
 * Front-panel CZ algorithm shortcuts.
 * 
 * These map to a `(CzWaveform, WindowType)` pair.
 */
export type CzAlgo = "saw" | "square" | "pulse" | "doubleSine" | "sawPulse" | "reso1" | "reso2" | "reso3"

/**
 * Low-level CZ waveform selector.
 */
export type CzWaveform = "saw" | "square" | "pulse" | "null" | "sinePulse" | "sawPulse" | "multiSine" | "pulse2"

/**
 * Per-line CZ slot controls.
 * 
 * Slot A/Slot B alternate per cycle in CZ mode. Setting both slots to the
 * same waveform effectively yields single-wave behavior.
 */
export type CzLineParams = { slotAWaveform: CzWaveform; slotBWaveform: CzWaveform; window: WindowType }

/**
 * Flat algorithm selector — unifies CZ waveforms and warp variants.
 * Serializes as plain camelCase string (e.g., "saw", "bend", "sync").
 */
export type Algo = "saw" | "square" | "pulse" | "null" | "sinePulse" | "sawPulse" | "multiSine" | "pulse2" | "cz101" | "bend" | "sync" | "pinch" | "fold" | "skew" | "quantize" | "twist" | "clip" | "ripple" | "mirror" | "fof" | "karpunk" | "sine"

/**
 * Window type applied to oscillator output
 */
export type WindowType = "off" | "saw" | "triangle" | "trapezoid" | "pulse" | "doubleSaw"

/**
 * Line select
 */
export type LineSelect = "L1+L2" | "L1" | "L2" | "L1+L1'" | "L1+L2'"

/**
 * Modulation mode
 */
export type ModMode = "normal" | "ring" | "noise"

/**
 * Polyphony mode
 */
export type PolyMode = "poly8" | "mono"

/**
 * Velocity routing target
 */
export type VelocityTarget = "amp" | "dcw" | "both" | 
/**
 * JS "off" means velocity is ignored (worklet passes 0 velocity)
 */
"off"

/**
 * LFO waveform
 */
export type LfoWaveform = "sine" | "triangle" | "square" | "saw"

/**
 * Filter type
 */
export type FilterType = "lp" | "hp" | "bp"

/**
 * Portamento mode
 */
export type PortamentoMode = "rate" | "time"

/**
 * LFO target
 */
export type LfoTarget = "pitch" | "dcw" | "dca" | "filter"

/**
 * Chorus parameters
 */
export type ChorusParams = { rate: number; depth: number; mix: number }

/**
 * Delay parameters
 */
export type DelayParams = { time: number; feedback: number; mix: number }

/**
 * Reverb parameters
 */
export type ReverbParams = { size: number; mix: number }

/**
 * Vibrato parameters
 */
export type VibratoParams = { enabled: boolean; 
/**
 * Waveform as integer 1-4 (JS sends a number: 1=sine 2=tri 3=sq 4=saw)
 */
waveform: number; 
/**
 * Rate in Hz
 */
rate: number; 
/**
 * Depth in "per mille" (divide by 1000 for pitch multiplier)
 */
depth: number; 
/**
 * Delay in milliseconds
 */
delay: number }

/**
 * Portamento parameters
 */
export type PortamentoParams = { enabled: boolean; mode: PortamentoMode; rate: number; time: number }

/**
 * LFO parameters
 */
export type LfoParams = { enabled: boolean; waveform: LfoWaveform; 
/**
 * Rate in Hz
 */
rate: number; 
/**
 * Depth [0, 1]
 */
depth: number; target: LfoTarget; 
/**
 * DC offset/bias applied to LFO output [-1, 1]
 */
offset?: number }

/**
 * Filter parameters
 */
export type FilterParams = { enabled: boolean; type: FilterType; cutoff: number; resonance: number; envAmount: number }

/**
 * Per-line parameters
 */
export type LineParams = { algo: Algo; algo2: Algo | null; algoBlend: number; dcwComp: number; window: WindowType; dcaBase: number; dcwBase: number; dcoDepth: number; modulation: number; detuneCents: number; octave: number; dcoEnv: StepEnvData; dcwEnv: StepEnvData; dcaEnv: StepEnvData; keyFollow: number; cz?: CzLineParams }

/**
 * Flat algorithm selection unifying waveforms and warp variants.
 * Serializes as plain camelCase string (e.g., "saw", "bend", "sync").
 */
export type AlgoRefV1 = "czSaw" | "czSquare" | "czPulse" | "czDoubleSine" | "czSawPulse" | "czReso1" | "czReso2" | "czReso3" | "saw" | "square" | "pulse" | "null" | "sinePulse" | "sawPulse" | "multiSine" | "pulse2" | "cz101" | "bend" | "sync" | "pinch" | "fold" | "skew" | "quantize" | "twist" | "clip" | "ripple" | "mirror" | "fof" | "karpunk" | "sine"

/**
 * Describes one control surfaced by an algorithm package.
 */
export type AlgoControlV1 = { id: string; label: string; min: number; max: number; default: number }

/**
 * Complete algorithm package definition.
 */
export type AlgoDefinitionV1 = { id: AlgoRefV1; name: string; iconPath: string; visible: boolean; controls: AlgoControlV1 }

/**
 * UI catalog entry for algorithm pickers.
 * 
 * This is exported to TypeScript so frontend option labels/icons are Rust-owned.
 */
export type AlgoUiEntryV1 = { id: AlgoRefV1; label: string; iconPath: string; visible: boolean }

/**
 * Top-level synth parameters (mirrors this.params in the JS)
 */
export type SynthParams = { lineSelect: LineSelect; modMode: ModMode; octave: number; line1: LineParams; line2: LineParams; intPmAmount: number; intPmRatio: number; extPmAmount: number; pmPre: boolean; frequency: number; volume: number; polyMode: PolyMode; legato: boolean; velocityTarget: VelocityTarget; chorus: ChorusParams; delay: DelayParams; reverb: ReverbParams; vibrato: VibratoParams; portamento: PortamentoParams; lfo: LfoParams; filter: FilterParams; 
/**
 * Pitch bend wheel range in semitones (1-24). Default 2.
 */
pitchBendRange?: number; 
/**
 * How much the mod wheel adds to vibrato depth (0-99 UI units).
 * When mod wheel is at max (1.0), vibrato depth is boosted by this amount.
 */
modWheelVibratoDepth?: number }

/**
 * Canonical, versioned synth preset wire contract.
 */
export type SynthPresetV1 = { schemaVersion?: number; params: SynthParams }

/**
 * TODO: Remove this compatibility shape after all preset reads/writes migrate to `SynthPresetV1`.
 * Temporary compatibility shape matching current flat TS preset storage.
 */
export type SynthPresetFlatV1 = { schemaVersion?: number; warpAAmount: number; warpBAmount: number; warpAAlgo: AlgoRefV1; warpBAlgo: AlgoRefV1; algo2A: AlgoRefV1 | null; algo2B: AlgoRefV1 | null; algoBlendA: number; algoBlendB: number; intPmAmount: number; intPmRatio: number; phaseModEnabled?: boolean; pmPre: boolean; windowType: WindowType; volume: number; line1Level: number; line2Level: number; line1Octave: number; line2Octave: number; line1Detune: number; line2Detune: number; line1DcoDepth: number; line2DcoDepth: number; line1DcwComp: number; line2DcwComp: number; line1DcoEnv: StepEnvData; line1DcwEnv: StepEnvData; line1DcaEnv: StepEnvData; line2DcoEnv: StepEnvData; line2DcwEnv: StepEnvData; line2DcaEnv: StepEnvData; line1CzSlotAWaveform?: CzWaveform | null; line1CzSlotBWaveform?: CzWaveform | null; line1CzWindow?: WindowType | null; line2CzSlotAWaveform?: CzWaveform | null; line2CzSlotBWaveform?: CzWaveform | null; line2CzWindow?: WindowType | null; lineSelect: LineSelect; modMode: ModMode; polyMode: PolyMode; legato: boolean; velocityTarget: VelocityTarget; chorusEnabled: boolean; chorusRate: number; chorusDepth: number; chorusMix: number; delayEnabled: boolean; delayTime: number; delayFeedback: number; delayMix: number; reverbEnabled: boolean; reverbSize: number; reverbMix: number; line1DcwKeyFollow: number; line1DcaKeyFollow?: number; line2DcwKeyFollow: number; line2DcaKeyFollow?: number; vibratoEnabled: boolean; vibratoWave: number; vibratoRate: number; vibratoDepth: number; vibratoDelay: number; portamentoEnabled: boolean; portamentoMode: PortamentoMode; portamentoRate: number; portamentoTime: number; lfoEnabled: boolean; lfoWaveform: LfoWaveform; lfoRate: number; lfoDepth: number; lfoOffset: number; lfoTarget: LfoTarget; filterEnabled: boolean; filterType: FilterType; filterCutoff: number; filterResonance: number; filterEnvAmount: number; pitchBendRange?: number; modWheelVibratoDepth?: number }

/** Rust-owned algorithm UI catalog. */
export const ALGO_UI_CATALOG_V1: AlgoUiEntryV1[] = [
  {
    "id": "czSaw",
    "label": "CZ Saw",
    "iconPath": "M4,4 L20,20",
    "visible": true
  },
  {
    "id": "czSquare",
    "label": "CZ Square",
    "iconPath": "M4,4 L12,4 L12,20 L20,20",
    "visible": true
  },
  {
    "id": "czPulse",
    "label": "CZ Pulse",
    "iconPath": "M4,20 L8,20 L8,4 L16,4 L16,20 L20,20",
    "visible": true
  },
  {
    "id": "czDoubleSine",
    "label": "CZ DoubleSine",
    "iconPath": "M4,12 C6,4 10,4 12,12 C14,20 18,20 20,12",
    "visible": true
  },
  {
    "id": "czSawPulse",
    "label": "CZ SawPulse",
    "iconPath": "M4,20 L7,4 L9,20 L12,4 L14,20 L17,4 L20,20",
    "visible": true
  },
  {
    "id": "czReso1",
    "label": "CZ Reso1",
    "iconPath": "M4,18 C7,6 9,6 12,18 C15,6 17,6 20,18",
    "visible": true
  },
  {
    "id": "czReso2",
    "label": "CZ Reso2",
    "iconPath": "M4,18 C6,4 10,4 12,12 C14,20 18,20 20,6",
    "visible": true
  },
  {
    "id": "czReso3",
    "label": "CZ Reso3",
    "iconPath": "M4,12 L8,4 L12,20 L16,4 L20,12",
    "visible": true
  },
  {
    "id": "bend",
    "label": "Bend",
    "iconPath": "M4,18 C10,18 14,10 20,4",
    "visible": true
  },
  {
    "id": "sync",
    "label": "Sync",
    "iconPath": "M4,20 L8,4 L8,20 L12,4 L12,20 L16,4 L16,20 L20,4",
    "visible": true
  },
  {
    "id": "pinch",
    "label": "Pinch",
    "iconPath": "M4,12 C8,4 10,12 12,12 C14,12 16,20 20,12",
    "visible": true
  },
  {
    "id": "fold",
    "label": "Fold",
    "iconPath": "M4,20 L8,4 L12,20 L16,4 L20,20",
    "visible": true
  },
  {
    "id": "skew",
    "label": "Skew",
    "iconPath": "M4,20 L10,6 L20,4",
    "visible": true
  },
  {
    "id": "twist",
    "label": "Twist",
    "iconPath": "M4,12 C8,2 16,22 20,12",
    "visible": true
  },
  {
    "id": "clip",
    "label": "Clip",
    "iconPath": "M4,16 L8,16 L8,8 L16,8 L16,16 L20,16",
    "visible": true
  },
  {
    "id": "ripple",
    "label": "Ripple",
    "iconPath": "M4,12 C6,8 8,16 10,12 C12,8 14,16 16,12 C18,8 19,13 20,12",
    "visible": true
  },
  {
    "id": "mirror",
    "label": "Mirror",
    "iconPath": "M4,20 L12,4 L20,20",
    "visible": true
  },
  {
    "id": "karpunk",
    "label": "Karpunk",
    "iconPath": "M4,16 C8,2 12,22 16,8 L20,12",
    "visible": true
  },
  {
    "id": "fof",
    "label": "FOF",
    "iconPath": "M4,16 C8,4 10,4 12,16 C14,4 16,4 20,16",
    "visible": true
  },
  {
    "id": "cz101",
    "label": "CZ101",
    "iconPath": "M4,12 L20,12",
    "visible": false
  }
];

/** Rust-owned algorithm definitions and control defaults. */
export const ALGO_DEFINITIONS_V1 = [
  {
    "id": "czSaw",
    "name": "CZ Saw",
    "iconPath": "M4,4 L20,20",
    "visible": true,
    "controls": [
      {
        "id": "waveform1",
        "label": "Waveform 1",
        "min": 0.0,
        "max": 7.0,
        "default": 0.0
      },
      {
        "id": "waveform2",
        "label": "Waveform 2",
        "min": 0.0,
        "max": 7.0,
        "default": 0.0
      },
      {
        "id": "windowFunction",
        "label": "Window Function",
        "min": 0.0,
        "max": 5.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "czSquare",
    "name": "CZ Square",
    "iconPath": "M4,4 L12,4 L12,20 L20,20",
    "visible": true,
    "controls": [
      {
        "id": "waveform1",
        "label": "Waveform 1",
        "min": 0.0,
        "max": 7.0,
        "default": 1.0
      },
      {
        "id": "waveform2",
        "label": "Waveform 2",
        "min": 0.0,
        "max": 7.0,
        "default": 1.0
      },
      {
        "id": "windowFunction",
        "label": "Window Function",
        "min": 0.0,
        "max": 5.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "czPulse",
    "name": "CZ Pulse",
    "iconPath": "M4,20 L8,20 L8,4 L16,4 L16,20 L20,20",
    "visible": true,
    "controls": [
      {
        "id": "waveform1",
        "label": "Waveform 1",
        "min": 0.0,
        "max": 7.0,
        "default": 2.0
      },
      {
        "id": "waveform2",
        "label": "Waveform 2",
        "min": 0.0,
        "max": 7.0,
        "default": 2.0
      },
      {
        "id": "windowFunction",
        "label": "Window Function",
        "min": 0.0,
        "max": 5.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "czDoubleSine",
    "name": "CZ DoubleSine",
    "iconPath": "M4,12 C6,4 10,4 12,12 C14,20 18,20 20,12",
    "visible": true,
    "controls": [
      {
        "id": "waveform1",
        "label": "Waveform 1",
        "min": 0.0,
        "max": 7.0,
        "default": 4.0
      },
      {
        "id": "waveform2",
        "label": "Waveform 2",
        "min": 0.0,
        "max": 7.0,
        "default": 4.0
      },
      {
        "id": "windowFunction",
        "label": "Window Function",
        "min": 0.0,
        "max": 5.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "czSawPulse",
    "name": "CZ SawPulse",
    "iconPath": "M4,20 L7,4 L9,20 L12,4 L14,20 L17,4 L20,20",
    "visible": true,
    "controls": [
      {
        "id": "waveform1",
        "label": "Waveform 1",
        "min": 0.0,
        "max": 7.0,
        "default": 5.0
      },
      {
        "id": "waveform2",
        "label": "Waveform 2",
        "min": 0.0,
        "max": 7.0,
        "default": 5.0
      },
      {
        "id": "windowFunction",
        "label": "Window Function",
        "min": 0.0,
        "max": 5.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "czReso1",
    "name": "CZ Reso1",
    "iconPath": "M4,18 C7,6 9,6 12,18 C15,6 17,6 20,18",
    "visible": true,
    "controls": [
      {
        "id": "waveform1",
        "label": "Waveform 1",
        "min": 0.0,
        "max": 7.0,
        "default": 6.0
      },
      {
        "id": "waveform2",
        "label": "Waveform 2",
        "min": 0.0,
        "max": 7.0,
        "default": 6.0
      },
      {
        "id": "windowFunction",
        "label": "Window Function",
        "min": 0.0,
        "max": 5.0,
        "default": 1.0
      }
    ]
  },
  {
    "id": "czReso2",
    "name": "CZ Reso2",
    "iconPath": "M4,18 C6,4 10,4 12,12 C14,20 18,20 20,6",
    "visible": true,
    "controls": [
      {
        "id": "waveform1",
        "label": "Waveform 1",
        "min": 0.0,
        "max": 7.0,
        "default": 6.0
      },
      {
        "id": "waveform2",
        "label": "Waveform 2",
        "min": 0.0,
        "max": 7.0,
        "default": 6.0
      },
      {
        "id": "windowFunction",
        "label": "Window Function",
        "min": 0.0,
        "max": 5.0,
        "default": 2.0
      }
    ]
  },
  {
    "id": "czReso3",
    "name": "CZ Reso3",
    "iconPath": "M4,12 L8,4 L12,20 L16,4 L20,12",
    "visible": true,
    "controls": [
      {
        "id": "waveform1",
        "label": "Waveform 1",
        "min": 0.0,
        "max": 7.0,
        "default": 6.0
      },
      {
        "id": "waveform2",
        "label": "Waveform 2",
        "min": 0.0,
        "max": 7.0,
        "default": 6.0
      },
      {
        "id": "windowFunction",
        "label": "Window Function",
        "min": 0.0,
        "max": 5.0,
        "default": 3.0
      }
    ]
  },
  {
    "id": "bend",
    "name": "Bend",
    "iconPath": "M4,18 C10,18 14,10 20,4",
    "visible": true,
    "controls": [
      {
        "id": "warpAmount",
        "label": "Warp Amount",
        "min": 0.0,
        "max": 1.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "sync",
    "name": "Sync",
    "iconPath": "M4,20 L8,4 L8,20 L12,4 L12,20 L16,4 L16,20 L20,4",
    "visible": true,
    "controls": [
      {
        "id": "warpAmount",
        "label": "Warp Amount",
        "min": 0.0,
        "max": 1.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "pinch",
    "name": "Pinch",
    "iconPath": "M4,12 C8,4 10,12 12,12 C14,12 16,20 20,12",
    "visible": true,
    "controls": [
      {
        "id": "warpAmount",
        "label": "Warp Amount",
        "min": 0.0,
        "max": 1.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "fold",
    "name": "Fold",
    "iconPath": "M4,20 L8,4 L12,20 L16,4 L20,20",
    "visible": true,
    "controls": [
      {
        "id": "warpAmount",
        "label": "Warp Amount",
        "min": 0.0,
        "max": 1.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "skew",
    "name": "Skew",
    "iconPath": "M4,20 L10,6 L20,4",
    "visible": true,
    "controls": [
      {
        "id": "warpAmount",
        "label": "Warp Amount",
        "min": 0.0,
        "max": 1.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "twist",
    "name": "Twist",
    "iconPath": "M4,12 C8,2 16,22 20,12",
    "visible": true,
    "controls": [
      {
        "id": "warpAmount",
        "label": "Warp Amount",
        "min": 0.0,
        "max": 1.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "clip",
    "name": "Clip",
    "iconPath": "M4,16 L8,16 L8,8 L16,8 L16,16 L20,16",
    "visible": true,
    "controls": [
      {
        "id": "warpAmount",
        "label": "Warp Amount",
        "min": 0.0,
        "max": 1.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "ripple",
    "name": "Ripple",
    "iconPath": "M4,12 C6,8 8,16 10,12 C12,8 14,16 16,12 C18,8 19,13 20,12",
    "visible": true,
    "controls": [
      {
        "id": "warpAmount",
        "label": "Warp Amount",
        "min": 0.0,
        "max": 1.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "mirror",
    "name": "Mirror",
    "iconPath": "M4,20 L12,4 L20,20",
    "visible": true,
    "controls": [
      {
        "id": "warpAmount",
        "label": "Warp Amount",
        "min": 0.0,
        "max": 1.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "karpunk",
    "name": "Karpunk",
    "iconPath": "M4,16 C8,2 12,22 16,8 L20,12",
    "visible": true,
    "controls": []
  },
  {
    "id": "fof",
    "name": "FOF",
    "iconPath": "M4,16 C8,4 10,4 12,16 C14,4 16,4 20,16",
    "visible": true,
    "controls": [
      {
        "id": "warpAmount",
        "label": "Warp Amount",
        "min": 0.0,
        "max": 1.0,
        "default": 0.0
      }
    ]
  },
  {
    "id": "cz101",
    "name": "CZ101",
    "iconPath": "M4,12 L20,12",
    "visible": false,
    "controls": [
      {
        "id": "waveform1",
        "label": "Waveform 1",
        "min": 0.0,
        "max": 7.0,
        "default": 0.0
      },
      {
        "id": "waveform2",
        "label": "Waveform 2",
        "min": 0.0,
        "max": 7.0,
        "default": 0.0
      },
      {
        "id": "windowFunction",
        "label": "Window Function",
        "min": 0.0,
        "max": 5.0,
        "default": 0.0
      }
    ]
  }
];
